spring:
  application:
    name: StudentProjectSpringDemo
  ## Cau hinh ket noi database MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/studentdemo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true


